// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"is_halted",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("print_reg", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+4+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+36,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"is_halted",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("print_reg", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+39+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("cpu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+71,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+73,0,"is_halted",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("print_reg", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+74+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBit(c+106,0,"is_stall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+107,0,"forward_ecall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+108,0,"forward_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+109,0,"forward_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+110,0,"current_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+111,0,"next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+112,0,"instruction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+113,0,"mem_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"mem_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"alu_src",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+118,0,"alu_op",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+119,0,"is_ecall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"halt_sim",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+121,0,"rs1_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+122,0,"rs1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+123,0,"rs2_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+124,0,"imm_gen_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+125,0,"ecall_forward_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+126,0,"alu_control",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+127,0,"alu_in_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+128,0,"alu_result",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+129,0,"alu_forward_data_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+130,0,"alu_forward_data_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+131,0,"mem_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+132,0,"writeback_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+133,0,"IF_ID_inst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+134,0,"ID_EX_alu_op",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+135,0,"ID_EX_alu_src",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"ID_EX_mem_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"ID_EX_mem_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+138,0,"ID_EX_mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"ID_EX_reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"ID_EX_is_halted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+141,0,"ID_EX_rs1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+142,0,"ID_EX_rs2_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+143,0,"ID_EX_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+144,0,"ID_EX_ALU_ctrl_unit_input",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"ID_EX_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+146,0,"ID_EX_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+147,0,"ID_EX_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+148,0,"EX_MEM_mem_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"EX_MEM_mem_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"EX_MEM_mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"EX_MEM_reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"EX_MEM_is_halted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+153,0,"EX_MEM_alu_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+154,0,"EX_MEM_dmem_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+155,0,"EX_MEM_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+156,0,"MEM_WB_mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+157,0,"MEM_WB_reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"MEM_WB_is_halted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+159,0,"MEM_WB_mem_to_reg_src_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+160,0,"MEM_WB_mem_to_reg_src_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+161,0,"MEM_WB_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("alu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+162,0,"alu_control",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+163,0,"alu_in_1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+164,0,"alu_in_2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+165,0,"alu_result",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("alu_ctrl_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+166,0,"functs",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+167,0,"alu_op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+168,0,"alu_control",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->popPrefix();
    tracep->pushPrefix("ctrl_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+169,0,"opcode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+170,0,"mem_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"mem_to_reg",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"mem_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"alu_src",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"reg_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+175,0,"alu_op",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+176,0,"is_ecall",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("dmem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+299,0,"MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+177,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+178,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+179,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+180,0,"din",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+181,0,"mem_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+182,0,"mem_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+183,0,"dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+184,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+185,0,"dmem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("forwarding_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+186,0,"EX_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+187,0,"EX_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+188,0,"MEM_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+189,0,"MEM_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+190,0,"WB_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+191,0,"WB_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+192,0,"forward_ecall",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+193,0,"forward_rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+194,0,"forward_rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("imem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+300,0,"MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+195,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+196,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+197,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+198,0,"dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+199,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+200,0,"imem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("imm_gen", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+201,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"imm_gen_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,0,"opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->popPrefix();
    tracep->pushPrefix("pc", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+204,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+205,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+206,0,"is_stall",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+207,0,"next_pc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+208,0,"current_pc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("reg_file", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+209,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+210,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+211,0,"rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+212,0,"rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+213,0,"rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+214,0,"rd_din",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+215,0,"write_enable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+216,0,"rs1_dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+217,0,"rs2_dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("print_reg", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+218+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+250,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->pushPrefix("rf", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+251+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("stall_detection", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+283,0,"ID_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+284,0,"ID_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+285,0,"ID_opcode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+286,0,"EX_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+287,0,"EX_mem_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+288,0,"EX_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+289,0,"MEM_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+290,0,"MEM_mem_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+291,0,"MEM_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+292,0,"is_stall",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+293,0,"rs1_and_rs2_conditions",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+294,0,"rs1_conditions",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+295,0,"use_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+296,0,"use_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+297,0,"stall_by_load",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+298,0,"stall_by_ecall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+299,(0x4000U),32);
    bufp->fullIData(oldp+300,(0x400U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.reset));
    bufp->fullBit(oldp+2,(vlSelfRef.clk));
    bufp->fullBit(oldp+3,(vlSelfRef.is_halted));
    bufp->fullIData(oldp+4,(vlSelfRef.print_reg[0]),32);
    bufp->fullIData(oldp+5,(vlSelfRef.print_reg[1]),32);
    bufp->fullIData(oldp+6,(vlSelfRef.print_reg[2]),32);
    bufp->fullIData(oldp+7,(vlSelfRef.print_reg[3]),32);
    bufp->fullIData(oldp+8,(vlSelfRef.print_reg[4]),32);
    bufp->fullIData(oldp+9,(vlSelfRef.print_reg[5]),32);
    bufp->fullIData(oldp+10,(vlSelfRef.print_reg[6]),32);
    bufp->fullIData(oldp+11,(vlSelfRef.print_reg[7]),32);
    bufp->fullIData(oldp+12,(vlSelfRef.print_reg[8]),32);
    bufp->fullIData(oldp+13,(vlSelfRef.print_reg[9]),32);
    bufp->fullIData(oldp+14,(vlSelfRef.print_reg[10]),32);
    bufp->fullIData(oldp+15,(vlSelfRef.print_reg[11]),32);
    bufp->fullIData(oldp+16,(vlSelfRef.print_reg[12]),32);
    bufp->fullIData(oldp+17,(vlSelfRef.print_reg[13]),32);
    bufp->fullIData(oldp+18,(vlSelfRef.print_reg[14]),32);
    bufp->fullIData(oldp+19,(vlSelfRef.print_reg[15]),32);
    bufp->fullIData(oldp+20,(vlSelfRef.print_reg[16]),32);
    bufp->fullIData(oldp+21,(vlSelfRef.print_reg[17]),32);
    bufp->fullIData(oldp+22,(vlSelfRef.print_reg[18]),32);
    bufp->fullIData(oldp+23,(vlSelfRef.print_reg[19]),32);
    bufp->fullIData(oldp+24,(vlSelfRef.print_reg[20]),32);
    bufp->fullIData(oldp+25,(vlSelfRef.print_reg[21]),32);
    bufp->fullIData(oldp+26,(vlSelfRef.print_reg[22]),32);
    bufp->fullIData(oldp+27,(vlSelfRef.print_reg[23]),32);
    bufp->fullIData(oldp+28,(vlSelfRef.print_reg[24]),32);
    bufp->fullIData(oldp+29,(vlSelfRef.print_reg[25]),32);
    bufp->fullIData(oldp+30,(vlSelfRef.print_reg[26]),32);
    bufp->fullIData(oldp+31,(vlSelfRef.print_reg[27]),32);
    bufp->fullIData(oldp+32,(vlSelfRef.print_reg[28]),32);
    bufp->fullIData(oldp+33,(vlSelfRef.print_reg[29]),32);
    bufp->fullIData(oldp+34,(vlSelfRef.print_reg[30]),32);
    bufp->fullIData(oldp+35,(vlSelfRef.print_reg[31]),32);
    bufp->fullBit(oldp+36,(vlSelfRef.top__DOT__reset));
    bufp->fullBit(oldp+37,(vlSelfRef.top__DOT__clk));
    bufp->fullBit(oldp+38,(vlSelfRef.top__DOT__is_halted));
    bufp->fullIData(oldp+39,(vlSelfRef.top__DOT__print_reg[0]),32);
    bufp->fullIData(oldp+40,(vlSelfRef.top__DOT__print_reg[1]),32);
    bufp->fullIData(oldp+41,(vlSelfRef.top__DOT__print_reg[2]),32);
    bufp->fullIData(oldp+42,(vlSelfRef.top__DOT__print_reg[3]),32);
    bufp->fullIData(oldp+43,(vlSelfRef.top__DOT__print_reg[4]),32);
    bufp->fullIData(oldp+44,(vlSelfRef.top__DOT__print_reg[5]),32);
    bufp->fullIData(oldp+45,(vlSelfRef.top__DOT__print_reg[6]),32);
    bufp->fullIData(oldp+46,(vlSelfRef.top__DOT__print_reg[7]),32);
    bufp->fullIData(oldp+47,(vlSelfRef.top__DOT__print_reg[8]),32);
    bufp->fullIData(oldp+48,(vlSelfRef.top__DOT__print_reg[9]),32);
    bufp->fullIData(oldp+49,(vlSelfRef.top__DOT__print_reg[10]),32);
    bufp->fullIData(oldp+50,(vlSelfRef.top__DOT__print_reg[11]),32);
    bufp->fullIData(oldp+51,(vlSelfRef.top__DOT__print_reg[12]),32);
    bufp->fullIData(oldp+52,(vlSelfRef.top__DOT__print_reg[13]),32);
    bufp->fullIData(oldp+53,(vlSelfRef.top__DOT__print_reg[14]),32);
    bufp->fullIData(oldp+54,(vlSelfRef.top__DOT__print_reg[15]),32);
    bufp->fullIData(oldp+55,(vlSelfRef.top__DOT__print_reg[16]),32);
    bufp->fullIData(oldp+56,(vlSelfRef.top__DOT__print_reg[17]),32);
    bufp->fullIData(oldp+57,(vlSelfRef.top__DOT__print_reg[18]),32);
    bufp->fullIData(oldp+58,(vlSelfRef.top__DOT__print_reg[19]),32);
    bufp->fullIData(oldp+59,(vlSelfRef.top__DOT__print_reg[20]),32);
    bufp->fullIData(oldp+60,(vlSelfRef.top__DOT__print_reg[21]),32);
    bufp->fullIData(oldp+61,(vlSelfRef.top__DOT__print_reg[22]),32);
    bufp->fullIData(oldp+62,(vlSelfRef.top__DOT__print_reg[23]),32);
    bufp->fullIData(oldp+63,(vlSelfRef.top__DOT__print_reg[24]),32);
    bufp->fullIData(oldp+64,(vlSelfRef.top__DOT__print_reg[25]),32);
    bufp->fullIData(oldp+65,(vlSelfRef.top__DOT__print_reg[26]),32);
    bufp->fullIData(oldp+66,(vlSelfRef.top__DOT__print_reg[27]),32);
    bufp->fullIData(oldp+67,(vlSelfRef.top__DOT__print_reg[28]),32);
    bufp->fullIData(oldp+68,(vlSelfRef.top__DOT__print_reg[29]),32);
    bufp->fullIData(oldp+69,(vlSelfRef.top__DOT__print_reg[30]),32);
    bufp->fullIData(oldp+70,(vlSelfRef.top__DOT__print_reg[31]),32);
    bufp->fullBit(oldp+71,(vlSelfRef.top__DOT__cpu__DOT__reset));
    bufp->fullBit(oldp+72,(vlSelfRef.top__DOT__cpu__DOT__clk));
    bufp->fullBit(oldp+73,(vlSelfRef.top__DOT__cpu__DOT__is_halted));
    bufp->fullIData(oldp+74,(vlSelfRef.top__DOT__cpu__DOT__print_reg[0]),32);
    bufp->fullIData(oldp+75,(vlSelfRef.top__DOT__cpu__DOT__print_reg[1]),32);
    bufp->fullIData(oldp+76,(vlSelfRef.top__DOT__cpu__DOT__print_reg[2]),32);
    bufp->fullIData(oldp+77,(vlSelfRef.top__DOT__cpu__DOT__print_reg[3]),32);
    bufp->fullIData(oldp+78,(vlSelfRef.top__DOT__cpu__DOT__print_reg[4]),32);
    bufp->fullIData(oldp+79,(vlSelfRef.top__DOT__cpu__DOT__print_reg[5]),32);
    bufp->fullIData(oldp+80,(vlSelfRef.top__DOT__cpu__DOT__print_reg[6]),32);
    bufp->fullIData(oldp+81,(vlSelfRef.top__DOT__cpu__DOT__print_reg[7]),32);
    bufp->fullIData(oldp+82,(vlSelfRef.top__DOT__cpu__DOT__print_reg[8]),32);
    bufp->fullIData(oldp+83,(vlSelfRef.top__DOT__cpu__DOT__print_reg[9]),32);
    bufp->fullIData(oldp+84,(vlSelfRef.top__DOT__cpu__DOT__print_reg[10]),32);
    bufp->fullIData(oldp+85,(vlSelfRef.top__DOT__cpu__DOT__print_reg[11]),32);
    bufp->fullIData(oldp+86,(vlSelfRef.top__DOT__cpu__DOT__print_reg[12]),32);
    bufp->fullIData(oldp+87,(vlSelfRef.top__DOT__cpu__DOT__print_reg[13]),32);
    bufp->fullIData(oldp+88,(vlSelfRef.top__DOT__cpu__DOT__print_reg[14]),32);
    bufp->fullIData(oldp+89,(vlSelfRef.top__DOT__cpu__DOT__print_reg[15]),32);
    bufp->fullIData(oldp+90,(vlSelfRef.top__DOT__cpu__DOT__print_reg[16]),32);
    bufp->fullIData(oldp+91,(vlSelfRef.top__DOT__cpu__DOT__print_reg[17]),32);
    bufp->fullIData(oldp+92,(vlSelfRef.top__DOT__cpu__DOT__print_reg[18]),32);
    bufp->fullIData(oldp+93,(vlSelfRef.top__DOT__cpu__DOT__print_reg[19]),32);
    bufp->fullIData(oldp+94,(vlSelfRef.top__DOT__cpu__DOT__print_reg[20]),32);
    bufp->fullIData(oldp+95,(vlSelfRef.top__DOT__cpu__DOT__print_reg[21]),32);
    bufp->fullIData(oldp+96,(vlSelfRef.top__DOT__cpu__DOT__print_reg[22]),32);
    bufp->fullIData(oldp+97,(vlSelfRef.top__DOT__cpu__DOT__print_reg[23]),32);
    bufp->fullIData(oldp+98,(vlSelfRef.top__DOT__cpu__DOT__print_reg[24]),32);
    bufp->fullIData(oldp+99,(vlSelfRef.top__DOT__cpu__DOT__print_reg[25]),32);
    bufp->fullIData(oldp+100,(vlSelfRef.top__DOT__cpu__DOT__print_reg[26]),32);
    bufp->fullIData(oldp+101,(vlSelfRef.top__DOT__cpu__DOT__print_reg[27]),32);
    bufp->fullIData(oldp+102,(vlSelfRef.top__DOT__cpu__DOT__print_reg[28]),32);
    bufp->fullIData(oldp+103,(vlSelfRef.top__DOT__cpu__DOT__print_reg[29]),32);
    bufp->fullIData(oldp+104,(vlSelfRef.top__DOT__cpu__DOT__print_reg[30]),32);
    bufp->fullIData(oldp+105,(vlSelfRef.top__DOT__cpu__DOT__print_reg[31]),32);
    bufp->fullBit(oldp+106,(vlSelfRef.top__DOT__cpu__DOT__is_stall));
    bufp->fullCData(oldp+107,(vlSelfRef.top__DOT__cpu__DOT__forward_ecall),2);
    bufp->fullCData(oldp+108,(vlSelfRef.top__DOT__cpu__DOT__forward_rs1),2);
    bufp->fullCData(oldp+109,(vlSelfRef.top__DOT__cpu__DOT__forward_rs2),2);
    bufp->fullIData(oldp+110,(vlSelfRef.top__DOT__cpu__DOT__current_pc),32);
    bufp->fullIData(oldp+111,(vlSelfRef.top__DOT__cpu__DOT__next_pc),32);
    bufp->fullIData(oldp+112,(vlSelfRef.top__DOT__cpu__DOT__instruction),32);
    bufp->fullBit(oldp+113,(vlSelfRef.top__DOT__cpu__DOT__mem_read));
    bufp->fullBit(oldp+114,(vlSelfRef.top__DOT__cpu__DOT__mem_to_reg));
    bufp->fullBit(oldp+115,(vlSelfRef.top__DOT__cpu__DOT__mem_write));
    bufp->fullBit(oldp+116,(vlSelfRef.top__DOT__cpu__DOT__alu_src));
    bufp->fullBit(oldp+117,(vlSelfRef.top__DOT__cpu__DOT__reg_write));
    bufp->fullCData(oldp+118,(vlSelfRef.top__DOT__cpu__DOT__alu_op),2);
    bufp->fullBit(oldp+119,(vlSelfRef.top__DOT__cpu__DOT__is_ecall));
    bufp->fullBit(oldp+120,(vlSelfRef.top__DOT__cpu__DOT__halt_sim));
    bufp->fullCData(oldp+121,(vlSelfRef.top__DOT__cpu__DOT__rs1_in),5);
    bufp->fullIData(oldp+122,(vlSelfRef.top__DOT__cpu__DOT__rs1_data),32);
    bufp->fullIData(oldp+123,(vlSelfRef.top__DOT__cpu__DOT__rs2_data),32);
    bufp->fullIData(oldp+124,(vlSelfRef.top__DOT__cpu__DOT__imm_gen_out),32);
    bufp->fullIData(oldp+125,(vlSelfRef.top__DOT__cpu__DOT__ecall_forward_data),32);
    bufp->fullCData(oldp+126,(vlSelfRef.top__DOT__cpu__DOT__alu_control),4);
    bufp->fullIData(oldp+127,(vlSelfRef.top__DOT__cpu__DOT__alu_in_2),32);
    bufp->fullIData(oldp+128,(vlSelfRef.top__DOT__cpu__DOT__alu_result),32);
    bufp->fullIData(oldp+129,(vlSelfRef.top__DOT__cpu__DOT__alu_forward_data_1),32);
    bufp->fullIData(oldp+130,(vlSelfRef.top__DOT__cpu__DOT__alu_forward_data_2),32);
    bufp->fullIData(oldp+131,(vlSelfRef.top__DOT__cpu__DOT__mem_data),32);
    bufp->fullIData(oldp+132,(vlSelfRef.top__DOT__cpu__DOT__writeback_data),32);
    bufp->fullIData(oldp+133,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_inst),32);
    bufp->fullCData(oldp+134,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_alu_op),2);
    bufp->fullBit(oldp+135,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_alu_src));
    bufp->fullBit(oldp+136,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_write));
    bufp->fullBit(oldp+137,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_read));
    bufp->fullBit(oldp+138,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_to_reg));
    bufp->fullBit(oldp+139,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_reg_write));
    bufp->fullBit(oldp+140,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_halted));
    bufp->fullIData(oldp+141,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs1_data),32);
    bufp->fullIData(oldp+142,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs2_data),32);
    bufp->fullIData(oldp+143,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_imm),32);
    bufp->fullCData(oldp+144,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_ALU_ctrl_unit_input),4);
    bufp->fullCData(oldp+145,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs1),5);
    bufp->fullCData(oldp+146,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs2),5);
    bufp->fullCData(oldp+147,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rd),5);
    bufp->fullBit(oldp+148,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_write));
    bufp->fullBit(oldp+149,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_read));
    bufp->fullBit(oldp+150,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_to_reg));
    bufp->fullBit(oldp+151,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_reg_write));
    bufp->fullBit(oldp+152,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_is_halted));
    bufp->fullIData(oldp+153,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_alu_out),32);
    bufp->fullIData(oldp+154,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_dmem_data),32);
    bufp->fullCData(oldp+155,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_rd),5);
    bufp->fullBit(oldp+156,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg));
    bufp->fullBit(oldp+157,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_reg_write));
    bufp->fullBit(oldp+158,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_is_halted));
    bufp->fullIData(oldp+159,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1),32);
    bufp->fullIData(oldp+160,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_2),32);
    bufp->fullCData(oldp+161,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_rd),5);
    bufp->fullCData(oldp+162,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_control),4);
    bufp->fullIData(oldp+163,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_in_1),32);
    bufp->fullIData(oldp+164,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_in_2),32);
    bufp->fullIData(oldp+165,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_result),32);
    bufp->fullCData(oldp+166,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__functs),4);
    bufp->fullCData(oldp+167,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_op),2);
    bufp->fullCData(oldp+168,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_control),4);
    bufp->fullCData(oldp+169,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__opcode),7);
    bufp->fullBit(oldp+170,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read));
    bufp->fullBit(oldp+171,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_to_reg));
    bufp->fullBit(oldp+172,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write));
    bufp->fullBit(oldp+173,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src));
    bufp->fullBit(oldp+174,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__reg_write));
    bufp->fullCData(oldp+175,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__alu_op),2);
    bufp->fullBit(oldp+176,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall));
    bufp->fullBit(oldp+177,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__reset));
    bufp->fullBit(oldp+178,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__clk));
    bufp->fullIData(oldp+179,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__addr),32);
    bufp->fullIData(oldp+180,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__din),32);
    bufp->fullBit(oldp+181,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__mem_read));
    bufp->fullBit(oldp+182,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__mem_write));
    bufp->fullIData(oldp+183,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__dout),32);
    bufp->fullIData(oldp+184,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__i),32);
    bufp->fullIData(oldp+185,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__dmem_addr),32);
    bufp->fullCData(oldp+186,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__EX_rs1),5);
    bufp->fullCData(oldp+187,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__EX_rs2),5);
    bufp->fullCData(oldp+188,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_rd),5);
    bufp->fullBit(oldp+189,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_reg_write));
    bufp->fullCData(oldp+190,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__WB_rd),5);
    bufp->fullBit(oldp+191,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__WB_reg_write));
    bufp->fullCData(oldp+192,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__forward_ecall),2);
    bufp->fullCData(oldp+193,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__forward_rs1),2);
    bufp->fullCData(oldp+194,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__forward_rs2),2);
    bufp->fullBit(oldp+195,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__reset));
    bufp->fullBit(oldp+196,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__clk));
    bufp->fullIData(oldp+197,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__addr),32);
    bufp->fullIData(oldp+198,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__dout),32);
    bufp->fullIData(oldp+199,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__i),32);
    bufp->fullIData(oldp+200,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__imem_addr),32);
    bufp->fullIData(oldp+201,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__instruction),32);
    bufp->fullIData(oldp+202,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out),32);
    bufp->fullCData(oldp+203,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__opcode),7);
    bufp->fullBit(oldp+204,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__reset));
    bufp->fullBit(oldp+205,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__clk));
    bufp->fullBit(oldp+206,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__is_stall));
    bufp->fullIData(oldp+207,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__next_pc),32);
    bufp->fullIData(oldp+208,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__current_pc),32);
    bufp->fullBit(oldp+209,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__reset));
    bufp->fullBit(oldp+210,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__clk));
    bufp->fullCData(oldp+211,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1),5);
    bufp->fullCData(oldp+212,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2),5);
    bufp->fullCData(oldp+213,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd),5);
    bufp->fullIData(oldp+214,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd_din),32);
    bufp->fullBit(oldp+215,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__write_enable));
    bufp->fullIData(oldp+216,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1_dout),32);
    bufp->fullIData(oldp+217,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2_dout),32);
    bufp->fullIData(oldp+218,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[0]),32);
    bufp->fullIData(oldp+219,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[1]),32);
    bufp->fullIData(oldp+220,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[2]),32);
    bufp->fullIData(oldp+221,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[3]),32);
    bufp->fullIData(oldp+222,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[4]),32);
    bufp->fullIData(oldp+223,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[5]),32);
    bufp->fullIData(oldp+224,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[6]),32);
    bufp->fullIData(oldp+225,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[7]),32);
    bufp->fullIData(oldp+226,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[8]),32);
    bufp->fullIData(oldp+227,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[9]),32);
    bufp->fullIData(oldp+228,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[10]),32);
    bufp->fullIData(oldp+229,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[11]),32);
    bufp->fullIData(oldp+230,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[12]),32);
    bufp->fullIData(oldp+231,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[13]),32);
    bufp->fullIData(oldp+232,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[14]),32);
    bufp->fullIData(oldp+233,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[15]),32);
    bufp->fullIData(oldp+234,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[16]),32);
    bufp->fullIData(oldp+235,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[17]),32);
    bufp->fullIData(oldp+236,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[18]),32);
    bufp->fullIData(oldp+237,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[19]),32);
    bufp->fullIData(oldp+238,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[20]),32);
    bufp->fullIData(oldp+239,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[21]),32);
    bufp->fullIData(oldp+240,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[22]),32);
    bufp->fullIData(oldp+241,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[23]),32);
    bufp->fullIData(oldp+242,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[24]),32);
    bufp->fullIData(oldp+243,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[25]),32);
    bufp->fullIData(oldp+244,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[26]),32);
    bufp->fullIData(oldp+245,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[27]),32);
    bufp->fullIData(oldp+246,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[28]),32);
    bufp->fullIData(oldp+247,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[29]),32);
    bufp->fullIData(oldp+248,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[30]),32);
    bufp->fullIData(oldp+249,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[31]),32);
    bufp->fullIData(oldp+250,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__i),32);
    bufp->fullIData(oldp+251,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[0]),32);
    bufp->fullIData(oldp+252,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[1]),32);
    bufp->fullIData(oldp+253,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[2]),32);
    bufp->fullIData(oldp+254,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[3]),32);
    bufp->fullIData(oldp+255,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[4]),32);
    bufp->fullIData(oldp+256,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[5]),32);
    bufp->fullIData(oldp+257,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[6]),32);
    bufp->fullIData(oldp+258,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[7]),32);
    bufp->fullIData(oldp+259,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[8]),32);
    bufp->fullIData(oldp+260,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[9]),32);
    bufp->fullIData(oldp+261,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[10]),32);
    bufp->fullIData(oldp+262,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[11]),32);
    bufp->fullIData(oldp+263,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[12]),32);
    bufp->fullIData(oldp+264,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[13]),32);
    bufp->fullIData(oldp+265,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[14]),32);
    bufp->fullIData(oldp+266,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[15]),32);
    bufp->fullIData(oldp+267,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[16]),32);
    bufp->fullIData(oldp+268,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[17]),32);
    bufp->fullIData(oldp+269,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[18]),32);
    bufp->fullIData(oldp+270,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[19]),32);
    bufp->fullIData(oldp+271,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[20]),32);
    bufp->fullIData(oldp+272,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[21]),32);
    bufp->fullIData(oldp+273,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[22]),32);
    bufp->fullIData(oldp+274,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[23]),32);
    bufp->fullIData(oldp+275,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[24]),32);
    bufp->fullIData(oldp+276,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[25]),32);
    bufp->fullIData(oldp+277,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[26]),32);
    bufp->fullIData(oldp+278,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[27]),32);
    bufp->fullIData(oldp+279,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[28]),32);
    bufp->fullIData(oldp+280,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[29]),32);
    bufp->fullIData(oldp+281,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[30]),32);
    bufp->fullIData(oldp+282,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[31]),32);
    bufp->fullCData(oldp+283,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__ID_rs1),5);
    bufp->fullCData(oldp+284,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__ID_rs2),5);
    bufp->fullCData(oldp+285,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__ID_opcode),7);
    bufp->fullCData(oldp+286,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__EX_rd),5);
    bufp->fullBit(oldp+287,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__EX_mem_read));
    bufp->fullBit(oldp+288,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__EX_reg_write));
    bufp->fullCData(oldp+289,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__MEM_rd),5);
    bufp->fullBit(oldp+290,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__MEM_mem_read));
    bufp->fullBit(oldp+291,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__MEM_reg_write));
    bufp->fullBit(oldp+292,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__is_stall));
    bufp->fullBit(oldp+293,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__rs1_and_rs2_conditions));
    bufp->fullBit(oldp+294,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__rs1_conditions));
    bufp->fullBit(oldp+295,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__use_rs1));
    bufp->fullBit(oldp+296,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__use_rs2));
    bufp->fullBit(oldp+297,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__stall_by_load));
    bufp->fullBit(oldp+298,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__stall_by_ecall));
}
