// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelfRef.reset));
    bufp->chgBit(oldp+1,(vlSelfRef.clk));
    bufp->chgBit(oldp+2,(vlSelfRef.is_halted));
    bufp->chgIData(oldp+3,(vlSelfRef.print_reg[0]),32);
    bufp->chgIData(oldp+4,(vlSelfRef.print_reg[1]),32);
    bufp->chgIData(oldp+5,(vlSelfRef.print_reg[2]),32);
    bufp->chgIData(oldp+6,(vlSelfRef.print_reg[3]),32);
    bufp->chgIData(oldp+7,(vlSelfRef.print_reg[4]),32);
    bufp->chgIData(oldp+8,(vlSelfRef.print_reg[5]),32);
    bufp->chgIData(oldp+9,(vlSelfRef.print_reg[6]),32);
    bufp->chgIData(oldp+10,(vlSelfRef.print_reg[7]),32);
    bufp->chgIData(oldp+11,(vlSelfRef.print_reg[8]),32);
    bufp->chgIData(oldp+12,(vlSelfRef.print_reg[9]),32);
    bufp->chgIData(oldp+13,(vlSelfRef.print_reg[10]),32);
    bufp->chgIData(oldp+14,(vlSelfRef.print_reg[11]),32);
    bufp->chgIData(oldp+15,(vlSelfRef.print_reg[12]),32);
    bufp->chgIData(oldp+16,(vlSelfRef.print_reg[13]),32);
    bufp->chgIData(oldp+17,(vlSelfRef.print_reg[14]),32);
    bufp->chgIData(oldp+18,(vlSelfRef.print_reg[15]),32);
    bufp->chgIData(oldp+19,(vlSelfRef.print_reg[16]),32);
    bufp->chgIData(oldp+20,(vlSelfRef.print_reg[17]),32);
    bufp->chgIData(oldp+21,(vlSelfRef.print_reg[18]),32);
    bufp->chgIData(oldp+22,(vlSelfRef.print_reg[19]),32);
    bufp->chgIData(oldp+23,(vlSelfRef.print_reg[20]),32);
    bufp->chgIData(oldp+24,(vlSelfRef.print_reg[21]),32);
    bufp->chgIData(oldp+25,(vlSelfRef.print_reg[22]),32);
    bufp->chgIData(oldp+26,(vlSelfRef.print_reg[23]),32);
    bufp->chgIData(oldp+27,(vlSelfRef.print_reg[24]),32);
    bufp->chgIData(oldp+28,(vlSelfRef.print_reg[25]),32);
    bufp->chgIData(oldp+29,(vlSelfRef.print_reg[26]),32);
    bufp->chgIData(oldp+30,(vlSelfRef.print_reg[27]),32);
    bufp->chgIData(oldp+31,(vlSelfRef.print_reg[28]),32);
    bufp->chgIData(oldp+32,(vlSelfRef.print_reg[29]),32);
    bufp->chgIData(oldp+33,(vlSelfRef.print_reg[30]),32);
    bufp->chgIData(oldp+34,(vlSelfRef.print_reg[31]),32);
    bufp->chgBit(oldp+35,(vlSelfRef.top__DOT__reset));
    bufp->chgBit(oldp+36,(vlSelfRef.top__DOT__clk));
    bufp->chgBit(oldp+37,(vlSelfRef.top__DOT__is_halted));
    bufp->chgIData(oldp+38,(vlSelfRef.top__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+39,(vlSelfRef.top__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+40,(vlSelfRef.top__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+41,(vlSelfRef.top__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+42,(vlSelfRef.top__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+43,(vlSelfRef.top__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+44,(vlSelfRef.top__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+45,(vlSelfRef.top__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+46,(vlSelfRef.top__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+47,(vlSelfRef.top__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+48,(vlSelfRef.top__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+49,(vlSelfRef.top__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+50,(vlSelfRef.top__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+51,(vlSelfRef.top__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+52,(vlSelfRef.top__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+53,(vlSelfRef.top__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+54,(vlSelfRef.top__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+55,(vlSelfRef.top__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+56,(vlSelfRef.top__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+57,(vlSelfRef.top__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+58,(vlSelfRef.top__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+59,(vlSelfRef.top__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+60,(vlSelfRef.top__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+61,(vlSelfRef.top__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+62,(vlSelfRef.top__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+63,(vlSelfRef.top__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+64,(vlSelfRef.top__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+65,(vlSelfRef.top__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+66,(vlSelfRef.top__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+67,(vlSelfRef.top__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+68,(vlSelfRef.top__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+69,(vlSelfRef.top__DOT__print_reg[31]),32);
    bufp->chgBit(oldp+70,(vlSelfRef.top__DOT__cpu__DOT__reset));
    bufp->chgBit(oldp+71,(vlSelfRef.top__DOT__cpu__DOT__clk));
    bufp->chgBit(oldp+72,(vlSelfRef.top__DOT__cpu__DOT__is_halted));
    bufp->chgIData(oldp+73,(vlSelfRef.top__DOT__cpu__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+74,(vlSelfRef.top__DOT__cpu__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+75,(vlSelfRef.top__DOT__cpu__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+76,(vlSelfRef.top__DOT__cpu__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+77,(vlSelfRef.top__DOT__cpu__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+78,(vlSelfRef.top__DOT__cpu__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+79,(vlSelfRef.top__DOT__cpu__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+80,(vlSelfRef.top__DOT__cpu__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+81,(vlSelfRef.top__DOT__cpu__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+82,(vlSelfRef.top__DOT__cpu__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+83,(vlSelfRef.top__DOT__cpu__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+84,(vlSelfRef.top__DOT__cpu__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+85,(vlSelfRef.top__DOT__cpu__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+86,(vlSelfRef.top__DOT__cpu__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+87,(vlSelfRef.top__DOT__cpu__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+88,(vlSelfRef.top__DOT__cpu__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+89,(vlSelfRef.top__DOT__cpu__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+90,(vlSelfRef.top__DOT__cpu__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+91,(vlSelfRef.top__DOT__cpu__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+92,(vlSelfRef.top__DOT__cpu__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+93,(vlSelfRef.top__DOT__cpu__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+94,(vlSelfRef.top__DOT__cpu__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+95,(vlSelfRef.top__DOT__cpu__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+96,(vlSelfRef.top__DOT__cpu__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+97,(vlSelfRef.top__DOT__cpu__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+98,(vlSelfRef.top__DOT__cpu__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+99,(vlSelfRef.top__DOT__cpu__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+100,(vlSelfRef.top__DOT__cpu__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+101,(vlSelfRef.top__DOT__cpu__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+102,(vlSelfRef.top__DOT__cpu__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+103,(vlSelfRef.top__DOT__cpu__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+104,(vlSelfRef.top__DOT__cpu__DOT__print_reg[31]),32);
    bufp->chgBit(oldp+105,(vlSelfRef.top__DOT__cpu__DOT__PCWriteCond));
    bufp->chgBit(oldp+106,(vlSelfRef.top__DOT__cpu__DOT__PCWrite));
    bufp->chgBit(oldp+107,(vlSelfRef.top__DOT__cpu__DOT__IorD));
    bufp->chgBit(oldp+108,(vlSelfRef.top__DOT__cpu__DOT__MemRead));
    bufp->chgBit(oldp+109,(vlSelfRef.top__DOT__cpu__DOT__MemWrite));
    bufp->chgBit(oldp+110,(vlSelfRef.top__DOT__cpu__DOT__MemtoReg));
    bufp->chgBit(oldp+111,(vlSelfRef.top__DOT__cpu__DOT__IRWrite));
    bufp->chgBit(oldp+112,(vlSelfRef.top__DOT__cpu__DOT__PCSource));
    bufp->chgCData(oldp+113,(vlSelfRef.top__DOT__cpu__DOT__ALUOp),2);
    bufp->chgCData(oldp+114,(vlSelfRef.top__DOT__cpu__DOT__ALUSrcB),2);
    bufp->chgBit(oldp+115,(vlSelfRef.top__DOT__cpu__DOT__ALUSrcA));
    bufp->chgBit(oldp+116,(vlSelfRef.top__DOT__cpu__DOT__RegWrite));
    bufp->chgIData(oldp+117,(vlSelfRef.top__DOT__cpu__DOT__WriteData),32);
    bufp->chgIData(oldp+118,(vlSelfRef.top__DOT__cpu__DOT__MemData),32);
    bufp->chgIData(oldp+119,(vlSelfRef.top__DOT__cpu__DOT__regA_value),32);
    bufp->chgIData(oldp+120,(vlSelfRef.top__DOT__cpu__DOT__regB_value),32);
    bufp->chgIData(oldp+121,(vlSelfRef.top__DOT__cpu__DOT__immediate),32);
    bufp->chgIData(oldp+122,(vlSelfRef.top__DOT__cpu__DOT__current_pc),32);
    bufp->chgIData(oldp+123,(vlSelfRef.top__DOT__cpu__DOT__next_pc),32);
    bufp->chgIData(oldp+124,(vlSelfRef.top__DOT__cpu__DOT__addr),32);
    bufp->chgIData(oldp+125,(vlSelfRef.top__DOT__cpu__DOT__alu_in_1),32);
    bufp->chgIData(oldp+126,(vlSelfRef.top__DOT__cpu__DOT__alu_in_2),32);
    bufp->chgCData(oldp+127,(vlSelfRef.top__DOT__cpu__DOT__ALUControl),6);
    bufp->chgIData(oldp+128,(vlSelfRef.top__DOT__cpu__DOT__alu_result),32);
    bufp->chgBit(oldp+129,(vlSelfRef.top__DOT__cpu__DOT__alu_bcond));
    bufp->chgBit(oldp+130,(vlSelfRef.top__DOT__cpu__DOT__is_ecall));
    bufp->chgBit(oldp+131,(vlSelfRef.top__DOT__cpu__DOT__ecall_reg_cond));
    bufp->chgIData(oldp+132,(vlSelfRef.top__DOT__cpu__DOT__IR),32);
    bufp->chgIData(oldp+133,(vlSelfRef.top__DOT__cpu__DOT__MDR),32);
    bufp->chgIData(oldp+134,(vlSelfRef.top__DOT__cpu__DOT__A),32);
    bufp->chgIData(oldp+135,(vlSelfRef.top__DOT__cpu__DOT__B),32);
    bufp->chgIData(oldp+136,(vlSelfRef.top__DOT__cpu__DOT__ALUOut),32);
    bufp->chgCData(oldp+137,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__ALUControl),6);
    bufp->chgIData(oldp+138,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_in_1),32);
    bufp->chgIData(oldp+139,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_in_2),32);
    bufp->chgIData(oldp+140,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_result),32);
    bufp->chgBit(oldp+141,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_bcond));
    bufp->chgCData(oldp+142,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__functs),4);
    bufp->chgCData(oldp+143,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__opcode),7);
    bufp->chgCData(oldp+144,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__ALUOp),2);
    bufp->chgCData(oldp+145,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__ALUControl),6);
    bufp->chgBit(oldp+146,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__reset));
    bufp->chgBit(oldp+147,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__clk));
    bufp->chgCData(oldp+148,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__opcode),7);
    bufp->chgBit(oldp+149,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__PCWriteCond));
    bufp->chgBit(oldp+150,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__PCWrite));
    bufp->chgBit(oldp+151,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__IorD));
    bufp->chgBit(oldp+152,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__MemRead));
    bufp->chgBit(oldp+153,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__MemWrite));
    bufp->chgBit(oldp+154,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__MemtoReg));
    bufp->chgBit(oldp+155,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__IRWrite));
    bufp->chgBit(oldp+156,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__PCSource));
    bufp->chgCData(oldp+157,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__ALUOp),2);
    bufp->chgCData(oldp+158,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__ALUSrcB),2);
    bufp->chgBit(oldp+159,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__ALUSrcA));
    bufp->chgBit(oldp+160,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__RegWrite));
    bufp->chgBit(oldp+161,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall));
    bufp->chgCData(oldp+162,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__current_state),4);
    bufp->chgCData(oldp+163,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__next_state),4);
    bufp->chgCData(oldp+164,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_machine__DOT__opcode),7);
    bufp->chgCData(oldp+165,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_machine__DOT__current_state),4);
    bufp->chgCData(oldp+166,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_machine__DOT__next_state),4);
    bufp->chgCData(oldp+167,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__current_state),4);
    bufp->chgBit(oldp+168,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__PCWriteCond));
    bufp->chgBit(oldp+169,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__PCWrite));
    bufp->chgBit(oldp+170,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__IorD));
    bufp->chgBit(oldp+171,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__MemRead));
    bufp->chgBit(oldp+172,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__MemWrite));
    bufp->chgBit(oldp+173,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__MemtoReg));
    bufp->chgBit(oldp+174,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__IRWrite));
    bufp->chgBit(oldp+175,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__PCSource));
    bufp->chgCData(oldp+176,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__ALUOp),2);
    bufp->chgCData(oldp+177,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__ALUSrcB),2);
    bufp->chgBit(oldp+178,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__ALUSrcA));
    bufp->chgBit(oldp+179,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__state_to_control__DOT__RegWrite));
    bufp->chgIData(oldp+180,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__IR),32);
    bufp->chgIData(oldp+181,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out),32);
    bufp->chgCData(oldp+182,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__opcode),7);
    bufp->chgBit(oldp+183,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__reset));
    bufp->chgBit(oldp+184,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__clk));
    bufp->chgIData(oldp+185,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__addr),32);
    bufp->chgIData(oldp+186,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__din),32);
    bufp->chgBit(oldp+187,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__mem_read));
    bufp->chgBit(oldp+188,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__mem_write));
    bufp->chgIData(oldp+189,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__dout),32);
    bufp->chgIData(oldp+190,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__i),32);
    bufp->chgIData(oldp+191,(vlSelfRef.top__DOT__cpu__DOT__memory__DOT__mem_addr),32);
    bufp->chgBit(oldp+192,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__reset));
    bufp->chgBit(oldp+193,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__clk));
    bufp->chgBit(oldp+194,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__PCWrite));
    bufp->chgBit(oldp+195,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__PCWriteCond));
    bufp->chgBit(oldp+196,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__alu_bcond));
    bufp->chgIData(oldp+197,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__next_pc),32);
    bufp->chgIData(oldp+198,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__current_pc),32);
    bufp->chgBit(oldp+199,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__reset));
    bufp->chgBit(oldp+200,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__clk));
    bufp->chgCData(oldp+201,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1),5);
    bufp->chgCData(oldp+202,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2),5);
    bufp->chgCData(oldp+203,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd),5);
    bufp->chgIData(oldp+204,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd_din),32);
    bufp->chgBit(oldp+205,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__write_enable));
    bufp->chgBit(oldp+206,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__ecall_reg_cond));
    bufp->chgIData(oldp+207,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1_dout),32);
    bufp->chgIData(oldp+208,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2_dout),32);
    bufp->chgIData(oldp+209,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+210,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+211,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+212,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+213,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+214,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+215,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+216,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+217,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+218,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+219,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+220,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+221,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+222,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+223,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+224,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+225,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+226,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+227,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+228,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+229,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+230,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+231,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+232,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+233,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+234,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+235,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+236,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+237,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+238,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+239,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+240,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[31]),32);
    bufp->chgIData(oldp+241,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__i),32);
    bufp->chgIData(oldp+242,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[0]),32);
    bufp->chgIData(oldp+243,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[1]),32);
    bufp->chgIData(oldp+244,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[2]),32);
    bufp->chgIData(oldp+245,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[3]),32);
    bufp->chgIData(oldp+246,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[4]),32);
    bufp->chgIData(oldp+247,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[5]),32);
    bufp->chgIData(oldp+248,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[6]),32);
    bufp->chgIData(oldp+249,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[7]),32);
    bufp->chgIData(oldp+250,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[8]),32);
    bufp->chgIData(oldp+251,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[9]),32);
    bufp->chgIData(oldp+252,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[10]),32);
    bufp->chgIData(oldp+253,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[11]),32);
    bufp->chgIData(oldp+254,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[12]),32);
    bufp->chgIData(oldp+255,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[13]),32);
    bufp->chgIData(oldp+256,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[14]),32);
    bufp->chgIData(oldp+257,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[15]),32);
    bufp->chgIData(oldp+258,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[16]),32);
    bufp->chgIData(oldp+259,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[17]),32);
    bufp->chgIData(oldp+260,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[18]),32);
    bufp->chgIData(oldp+261,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[19]),32);
    bufp->chgIData(oldp+262,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[20]),32);
    bufp->chgIData(oldp+263,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[21]),32);
    bufp->chgIData(oldp+264,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[22]),32);
    bufp->chgIData(oldp+265,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[23]),32);
    bufp->chgIData(oldp+266,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[24]),32);
    bufp->chgIData(oldp+267,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[25]),32);
    bufp->chgIData(oldp+268,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[26]),32);
    bufp->chgIData(oldp+269,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[27]),32);
    bufp->chgIData(oldp+270,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[28]),32);
    bufp->chgIData(oldp+271,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[29]),32);
    bufp->chgIData(oldp+272,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[30]),32);
    bufp->chgIData(oldp+273,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[31]),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
