// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"is_halted",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("print_reg", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+4+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+36,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"is_halted",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("print_reg", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+39+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("cpu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+71,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+73,0,"is_halted",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("print_reg", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+74+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBit(c+106,0,"is_stall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+107,0,"forward_ecall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+108,0,"forward_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+109,0,"forward_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+110,0,"current_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+111,0,"next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+112,0,"instruction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+113,0,"predicted_next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+114,0,"predicted_branch_taken",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"is_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"is_jalr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+118,0,"pc_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+119,0,"mem_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"mem_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"alu_src",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+123,0,"reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+124,0,"alu_op",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+125,0,"is_ecall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"halt_sim",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+127,0,"rs1_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+128,0,"rs1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+129,0,"rs2_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+130,0,"imm_gen_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+131,0,"ecall_forward_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+132,0,"alu_control",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+133,0,"alu_in_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+134,0,"alu_result",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+135,0,"alu_bcond",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+136,0,"alu_forward_data_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+137,0,"alu_forward_data_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+138,0,"actual_branch_taken",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+139,0,"branch_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+140,0,"actual_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+141,0,"update_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+142,0,"prediction_wrong",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+143,0,"mem_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+144,0,"writeback_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+145,0,"IF_ID_inst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+146,0,"IF_ID_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+147,0,"IF_ID_predicted_next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+148,0,"IF_ID_predicted_branch_taken",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+149,0,"ID_EX_alu_op",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+150,0,"ID_EX_alu_src",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"ID_EX_mem_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"ID_EX_mem_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"ID_EX_mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+154,0,"ID_EX_reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"ID_EX_is_halted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+156,0,"ID_EX_is_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+157,0,"ID_EX_is_jalr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"ID_EX_branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"ID_EX_pc_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+160,0,"ID_EX_rs1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+161,0,"ID_EX_rs2_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+162,0,"ID_EX_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+163,0,"ID_EX_ALU_ctrl_unit_input",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+164,0,"ID_EX_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+165,0,"ID_EX_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+166,0,"ID_EX_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+167,0,"ID_EX_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+168,0,"ID_EX_predicted_next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+169,0,"ID_EX_predicted_branch_taken",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+170,0,"EX_MEM_mem_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"EX_MEM_mem_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"EX_MEM_mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"EX_MEM_reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"EX_MEM_is_halted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"EX_MEM_pc_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+176,0,"EX_MEM_alu_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+177,0,"EX_MEM_dmem_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+178,0,"EX_MEM_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+179,0,"EX_MEM_pc_plus_4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+180,0,"MEM_WB_mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+181,0,"MEM_WB_reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+182,0,"MEM_WB_is_halted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+183,0,"MEM_WB_pc_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+184,0,"MEM_WB_mem_to_reg_src_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+185,0,"MEM_WB_mem_to_reg_src_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+186,0,"MEM_WB_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+187,0,"MEM_WB_pc_plus_4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("alu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+188,0,"alu_control",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+189,0,"alu_in_1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+190,0,"alu_in_2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+191,0,"alu_result",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+192,0,"alu_bcond",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("alu_ctrl_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+193,0,"functs",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+194,0,"alu_op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+195,0,"alu_control",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->popPrefix();
    tracep->pushPrefix("branch_predictor", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+196,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+197,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+198,0,"update_pc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+199,0,"update_BTB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+200,0,"update_taken",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+201,0,"current_pc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"predicted_next_pc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+203,0,"predicted_branch_taken",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+204,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+205,0,"tag_match",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+206,0,"update_BTB_index",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+207,0,"update_PHT_index",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+208,0,"predict_BTB_index",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+209,0,"predict_PHT_index",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+210,0,"IF_ID_PHT_index",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+211,0,"ID_EX_PHT_index",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+212,0,"next_PHT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->pushPrefix("BTB", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+213+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("tag", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+245+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 26,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("valid", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBit(c+277+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0));
    }
    tracep->popPrefix();
    tracep->pushPrefix("PHT", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+309+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 1,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+341,0,"BHSR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("saturation_counter", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+342,0,"branch_taken",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+343,0,"current_state",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+344,0,"next_state",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("ctrl_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+345,0,"opcode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+346,0,"is_jal",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+347,0,"is_jalr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+348,0,"branch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+349,0,"pc_to_reg",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+350,0,"mem_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+351,0,"mem_to_reg",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+352,0,"mem_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+353,0,"alu_src",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+354,0,"reg_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+355,0,"alu_op",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+356,0,"is_ecall",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("dmem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+479,0,"MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+357,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+358,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+359,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+360,0,"din",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+361,0,"mem_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+362,0,"mem_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+363,0,"dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+364,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+365,0,"dmem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("forwarding_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+366,0,"EX_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+367,0,"EX_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+368,0,"MEM_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+369,0,"MEM_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+370,0,"WB_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+371,0,"WB_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+372,0,"forward_ecall",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+373,0,"forward_rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+374,0,"forward_rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("imem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+480,0,"MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+375,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+376,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+377,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+378,0,"dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+379,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+380,0,"imem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("imm_gen", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+381,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+382,0,"imm_gen_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+383,0,"opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->popPrefix();
    tracep->pushPrefix("pc", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+384,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+385,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+386,0,"is_stall",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+387,0,"next_pc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+388,0,"current_pc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("reg_file", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+389,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+390,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+391,0,"rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+392,0,"rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+393,0,"rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+394,0,"rd_din",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+395,0,"write_enable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+396,0,"rs1_dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+397,0,"rs2_dout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("print_reg", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+398+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+430,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->pushPrefix("rf", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+431+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("stall_detection", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+463,0,"ID_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+464,0,"ID_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+465,0,"ID_opcode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+466,0,"EX_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+467,0,"EX_mem_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+468,0,"EX_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+469,0,"MEM_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+470,0,"MEM_mem_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+471,0,"MEM_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+472,0,"is_stall",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+473,0,"rs1_and_rs2_conditions",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+474,0,"rs1_conditions",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+475,0,"use_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+476,0,"use_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+477,0,"stall_by_load",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+478,0,"stall_by_ecall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+479,(0x4000U),32);
    bufp->fullIData(oldp+480,(0x400U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.reset));
    bufp->fullBit(oldp+2,(vlSelfRef.clk));
    bufp->fullBit(oldp+3,(vlSelfRef.is_halted));
    bufp->fullIData(oldp+4,(vlSelfRef.print_reg[0]),32);
    bufp->fullIData(oldp+5,(vlSelfRef.print_reg[1]),32);
    bufp->fullIData(oldp+6,(vlSelfRef.print_reg[2]),32);
    bufp->fullIData(oldp+7,(vlSelfRef.print_reg[3]),32);
    bufp->fullIData(oldp+8,(vlSelfRef.print_reg[4]),32);
    bufp->fullIData(oldp+9,(vlSelfRef.print_reg[5]),32);
    bufp->fullIData(oldp+10,(vlSelfRef.print_reg[6]),32);
    bufp->fullIData(oldp+11,(vlSelfRef.print_reg[7]),32);
    bufp->fullIData(oldp+12,(vlSelfRef.print_reg[8]),32);
    bufp->fullIData(oldp+13,(vlSelfRef.print_reg[9]),32);
    bufp->fullIData(oldp+14,(vlSelfRef.print_reg[10]),32);
    bufp->fullIData(oldp+15,(vlSelfRef.print_reg[11]),32);
    bufp->fullIData(oldp+16,(vlSelfRef.print_reg[12]),32);
    bufp->fullIData(oldp+17,(vlSelfRef.print_reg[13]),32);
    bufp->fullIData(oldp+18,(vlSelfRef.print_reg[14]),32);
    bufp->fullIData(oldp+19,(vlSelfRef.print_reg[15]),32);
    bufp->fullIData(oldp+20,(vlSelfRef.print_reg[16]),32);
    bufp->fullIData(oldp+21,(vlSelfRef.print_reg[17]),32);
    bufp->fullIData(oldp+22,(vlSelfRef.print_reg[18]),32);
    bufp->fullIData(oldp+23,(vlSelfRef.print_reg[19]),32);
    bufp->fullIData(oldp+24,(vlSelfRef.print_reg[20]),32);
    bufp->fullIData(oldp+25,(vlSelfRef.print_reg[21]),32);
    bufp->fullIData(oldp+26,(vlSelfRef.print_reg[22]),32);
    bufp->fullIData(oldp+27,(vlSelfRef.print_reg[23]),32);
    bufp->fullIData(oldp+28,(vlSelfRef.print_reg[24]),32);
    bufp->fullIData(oldp+29,(vlSelfRef.print_reg[25]),32);
    bufp->fullIData(oldp+30,(vlSelfRef.print_reg[26]),32);
    bufp->fullIData(oldp+31,(vlSelfRef.print_reg[27]),32);
    bufp->fullIData(oldp+32,(vlSelfRef.print_reg[28]),32);
    bufp->fullIData(oldp+33,(vlSelfRef.print_reg[29]),32);
    bufp->fullIData(oldp+34,(vlSelfRef.print_reg[30]),32);
    bufp->fullIData(oldp+35,(vlSelfRef.print_reg[31]),32);
    bufp->fullBit(oldp+36,(vlSelfRef.top__DOT__reset));
    bufp->fullBit(oldp+37,(vlSelfRef.top__DOT__clk));
    bufp->fullBit(oldp+38,(vlSelfRef.top__DOT__is_halted));
    bufp->fullIData(oldp+39,(vlSelfRef.top__DOT__print_reg[0]),32);
    bufp->fullIData(oldp+40,(vlSelfRef.top__DOT__print_reg[1]),32);
    bufp->fullIData(oldp+41,(vlSelfRef.top__DOT__print_reg[2]),32);
    bufp->fullIData(oldp+42,(vlSelfRef.top__DOT__print_reg[3]),32);
    bufp->fullIData(oldp+43,(vlSelfRef.top__DOT__print_reg[4]),32);
    bufp->fullIData(oldp+44,(vlSelfRef.top__DOT__print_reg[5]),32);
    bufp->fullIData(oldp+45,(vlSelfRef.top__DOT__print_reg[6]),32);
    bufp->fullIData(oldp+46,(vlSelfRef.top__DOT__print_reg[7]),32);
    bufp->fullIData(oldp+47,(vlSelfRef.top__DOT__print_reg[8]),32);
    bufp->fullIData(oldp+48,(vlSelfRef.top__DOT__print_reg[9]),32);
    bufp->fullIData(oldp+49,(vlSelfRef.top__DOT__print_reg[10]),32);
    bufp->fullIData(oldp+50,(vlSelfRef.top__DOT__print_reg[11]),32);
    bufp->fullIData(oldp+51,(vlSelfRef.top__DOT__print_reg[12]),32);
    bufp->fullIData(oldp+52,(vlSelfRef.top__DOT__print_reg[13]),32);
    bufp->fullIData(oldp+53,(vlSelfRef.top__DOT__print_reg[14]),32);
    bufp->fullIData(oldp+54,(vlSelfRef.top__DOT__print_reg[15]),32);
    bufp->fullIData(oldp+55,(vlSelfRef.top__DOT__print_reg[16]),32);
    bufp->fullIData(oldp+56,(vlSelfRef.top__DOT__print_reg[17]),32);
    bufp->fullIData(oldp+57,(vlSelfRef.top__DOT__print_reg[18]),32);
    bufp->fullIData(oldp+58,(vlSelfRef.top__DOT__print_reg[19]),32);
    bufp->fullIData(oldp+59,(vlSelfRef.top__DOT__print_reg[20]),32);
    bufp->fullIData(oldp+60,(vlSelfRef.top__DOT__print_reg[21]),32);
    bufp->fullIData(oldp+61,(vlSelfRef.top__DOT__print_reg[22]),32);
    bufp->fullIData(oldp+62,(vlSelfRef.top__DOT__print_reg[23]),32);
    bufp->fullIData(oldp+63,(vlSelfRef.top__DOT__print_reg[24]),32);
    bufp->fullIData(oldp+64,(vlSelfRef.top__DOT__print_reg[25]),32);
    bufp->fullIData(oldp+65,(vlSelfRef.top__DOT__print_reg[26]),32);
    bufp->fullIData(oldp+66,(vlSelfRef.top__DOT__print_reg[27]),32);
    bufp->fullIData(oldp+67,(vlSelfRef.top__DOT__print_reg[28]),32);
    bufp->fullIData(oldp+68,(vlSelfRef.top__DOT__print_reg[29]),32);
    bufp->fullIData(oldp+69,(vlSelfRef.top__DOT__print_reg[30]),32);
    bufp->fullIData(oldp+70,(vlSelfRef.top__DOT__print_reg[31]),32);
    bufp->fullBit(oldp+71,(vlSelfRef.top__DOT__cpu__DOT__reset));
    bufp->fullBit(oldp+72,(vlSelfRef.top__DOT__cpu__DOT__clk));
    bufp->fullBit(oldp+73,(vlSelfRef.top__DOT__cpu__DOT__is_halted));
    bufp->fullIData(oldp+74,(vlSelfRef.top__DOT__cpu__DOT__print_reg[0]),32);
    bufp->fullIData(oldp+75,(vlSelfRef.top__DOT__cpu__DOT__print_reg[1]),32);
    bufp->fullIData(oldp+76,(vlSelfRef.top__DOT__cpu__DOT__print_reg[2]),32);
    bufp->fullIData(oldp+77,(vlSelfRef.top__DOT__cpu__DOT__print_reg[3]),32);
    bufp->fullIData(oldp+78,(vlSelfRef.top__DOT__cpu__DOT__print_reg[4]),32);
    bufp->fullIData(oldp+79,(vlSelfRef.top__DOT__cpu__DOT__print_reg[5]),32);
    bufp->fullIData(oldp+80,(vlSelfRef.top__DOT__cpu__DOT__print_reg[6]),32);
    bufp->fullIData(oldp+81,(vlSelfRef.top__DOT__cpu__DOT__print_reg[7]),32);
    bufp->fullIData(oldp+82,(vlSelfRef.top__DOT__cpu__DOT__print_reg[8]),32);
    bufp->fullIData(oldp+83,(vlSelfRef.top__DOT__cpu__DOT__print_reg[9]),32);
    bufp->fullIData(oldp+84,(vlSelfRef.top__DOT__cpu__DOT__print_reg[10]),32);
    bufp->fullIData(oldp+85,(vlSelfRef.top__DOT__cpu__DOT__print_reg[11]),32);
    bufp->fullIData(oldp+86,(vlSelfRef.top__DOT__cpu__DOT__print_reg[12]),32);
    bufp->fullIData(oldp+87,(vlSelfRef.top__DOT__cpu__DOT__print_reg[13]),32);
    bufp->fullIData(oldp+88,(vlSelfRef.top__DOT__cpu__DOT__print_reg[14]),32);
    bufp->fullIData(oldp+89,(vlSelfRef.top__DOT__cpu__DOT__print_reg[15]),32);
    bufp->fullIData(oldp+90,(vlSelfRef.top__DOT__cpu__DOT__print_reg[16]),32);
    bufp->fullIData(oldp+91,(vlSelfRef.top__DOT__cpu__DOT__print_reg[17]),32);
    bufp->fullIData(oldp+92,(vlSelfRef.top__DOT__cpu__DOT__print_reg[18]),32);
    bufp->fullIData(oldp+93,(vlSelfRef.top__DOT__cpu__DOT__print_reg[19]),32);
    bufp->fullIData(oldp+94,(vlSelfRef.top__DOT__cpu__DOT__print_reg[20]),32);
    bufp->fullIData(oldp+95,(vlSelfRef.top__DOT__cpu__DOT__print_reg[21]),32);
    bufp->fullIData(oldp+96,(vlSelfRef.top__DOT__cpu__DOT__print_reg[22]),32);
    bufp->fullIData(oldp+97,(vlSelfRef.top__DOT__cpu__DOT__print_reg[23]),32);
    bufp->fullIData(oldp+98,(vlSelfRef.top__DOT__cpu__DOT__print_reg[24]),32);
    bufp->fullIData(oldp+99,(vlSelfRef.top__DOT__cpu__DOT__print_reg[25]),32);
    bufp->fullIData(oldp+100,(vlSelfRef.top__DOT__cpu__DOT__print_reg[26]),32);
    bufp->fullIData(oldp+101,(vlSelfRef.top__DOT__cpu__DOT__print_reg[27]),32);
    bufp->fullIData(oldp+102,(vlSelfRef.top__DOT__cpu__DOT__print_reg[28]),32);
    bufp->fullIData(oldp+103,(vlSelfRef.top__DOT__cpu__DOT__print_reg[29]),32);
    bufp->fullIData(oldp+104,(vlSelfRef.top__DOT__cpu__DOT__print_reg[30]),32);
    bufp->fullIData(oldp+105,(vlSelfRef.top__DOT__cpu__DOT__print_reg[31]),32);
    bufp->fullBit(oldp+106,(vlSelfRef.top__DOT__cpu__DOT__is_stall));
    bufp->fullCData(oldp+107,(vlSelfRef.top__DOT__cpu__DOT__forward_ecall),2);
    bufp->fullCData(oldp+108,(vlSelfRef.top__DOT__cpu__DOT__forward_rs1),2);
    bufp->fullCData(oldp+109,(vlSelfRef.top__DOT__cpu__DOT__forward_rs2),2);
    bufp->fullIData(oldp+110,(vlSelfRef.top__DOT__cpu__DOT__current_pc),32);
    bufp->fullIData(oldp+111,(vlSelfRef.top__DOT__cpu__DOT__next_pc),32);
    bufp->fullIData(oldp+112,(vlSelfRef.top__DOT__cpu__DOT__instruction),32);
    bufp->fullIData(oldp+113,(vlSelfRef.top__DOT__cpu__DOT__predicted_next_pc),32);
    bufp->fullBit(oldp+114,(vlSelfRef.top__DOT__cpu__DOT__predicted_branch_taken));
    bufp->fullBit(oldp+115,(vlSelfRef.top__DOT__cpu__DOT__is_jal));
    bufp->fullBit(oldp+116,(vlSelfRef.top__DOT__cpu__DOT__is_jalr));
    bufp->fullBit(oldp+117,(vlSelfRef.top__DOT__cpu__DOT__branch));
    bufp->fullBit(oldp+118,(vlSelfRef.top__DOT__cpu__DOT__pc_to_reg));
    bufp->fullBit(oldp+119,(vlSelfRef.top__DOT__cpu__DOT__mem_read));
    bufp->fullBit(oldp+120,(vlSelfRef.top__DOT__cpu__DOT__mem_to_reg));
    bufp->fullBit(oldp+121,(vlSelfRef.top__DOT__cpu__DOT__mem_write));
    bufp->fullBit(oldp+122,(vlSelfRef.top__DOT__cpu__DOT__alu_src));
    bufp->fullBit(oldp+123,(vlSelfRef.top__DOT__cpu__DOT__reg_write));
    bufp->fullCData(oldp+124,(vlSelfRef.top__DOT__cpu__DOT__alu_op),2);
    bufp->fullBit(oldp+125,(vlSelfRef.top__DOT__cpu__DOT__is_ecall));
    bufp->fullBit(oldp+126,(vlSelfRef.top__DOT__cpu__DOT__halt_sim));
    bufp->fullCData(oldp+127,(vlSelfRef.top__DOT__cpu__DOT__rs1_in),5);
    bufp->fullIData(oldp+128,(vlSelfRef.top__DOT__cpu__DOT__rs1_data),32);
    bufp->fullIData(oldp+129,(vlSelfRef.top__DOT__cpu__DOT__rs2_data),32);
    bufp->fullIData(oldp+130,(vlSelfRef.top__DOT__cpu__DOT__imm_gen_out),32);
    bufp->fullIData(oldp+131,(vlSelfRef.top__DOT__cpu__DOT__ecall_forward_data),32);
    bufp->fullCData(oldp+132,(vlSelfRef.top__DOT__cpu__DOT__alu_control),4);
    bufp->fullIData(oldp+133,(vlSelfRef.top__DOT__cpu__DOT__alu_in_2),32);
    bufp->fullIData(oldp+134,(vlSelfRef.top__DOT__cpu__DOT__alu_result),32);
    bufp->fullBit(oldp+135,(vlSelfRef.top__DOT__cpu__DOT__alu_bcond));
    bufp->fullIData(oldp+136,(vlSelfRef.top__DOT__cpu__DOT__alu_forward_data_1),32);
    bufp->fullIData(oldp+137,(vlSelfRef.top__DOT__cpu__DOT__alu_forward_data_2),32);
    bufp->fullBit(oldp+138,(vlSelfRef.top__DOT__cpu__DOT__actual_branch_taken));
    bufp->fullIData(oldp+139,(vlSelfRef.top__DOT__cpu__DOT__branch_addr),32);
    bufp->fullIData(oldp+140,(vlSelfRef.top__DOT__cpu__DOT__actual_addr),32);
    bufp->fullIData(oldp+141,(vlSelfRef.top__DOT__cpu__DOT__update_pc),32);
    bufp->fullBit(oldp+142,(vlSelfRef.top__DOT__cpu__DOT__prediction_wrong));
    bufp->fullIData(oldp+143,(vlSelfRef.top__DOT__cpu__DOT__mem_data),32);
    bufp->fullIData(oldp+144,(vlSelfRef.top__DOT__cpu__DOT__writeback_data),32);
    bufp->fullIData(oldp+145,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_inst),32);
    bufp->fullIData(oldp+146,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_pc),32);
    bufp->fullIData(oldp+147,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_predicted_next_pc),32);
    bufp->fullBit(oldp+148,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_predicted_branch_taken));
    bufp->fullCData(oldp+149,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_alu_op),2);
    bufp->fullBit(oldp+150,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_alu_src));
    bufp->fullBit(oldp+151,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_write));
    bufp->fullBit(oldp+152,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_read));
    bufp->fullBit(oldp+153,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_to_reg));
    bufp->fullBit(oldp+154,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_reg_write));
    bufp->fullBit(oldp+155,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_halted));
    bufp->fullBit(oldp+156,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_jal));
    bufp->fullBit(oldp+157,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_jalr));
    bufp->fullBit(oldp+158,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_branch));
    bufp->fullBit(oldp+159,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_pc_to_reg));
    bufp->fullIData(oldp+160,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs1_data),32);
    bufp->fullIData(oldp+161,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs2_data),32);
    bufp->fullIData(oldp+162,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_imm),32);
    bufp->fullCData(oldp+163,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_ALU_ctrl_unit_input),4);
    bufp->fullCData(oldp+164,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs1),5);
    bufp->fullCData(oldp+165,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs2),5);
    bufp->fullCData(oldp+166,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rd),5);
    bufp->fullIData(oldp+167,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_pc),32);
    bufp->fullIData(oldp+168,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_predicted_next_pc),32);
    bufp->fullBit(oldp+169,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_predicted_branch_taken));
    bufp->fullBit(oldp+170,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_write));
    bufp->fullBit(oldp+171,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_read));
    bufp->fullBit(oldp+172,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_to_reg));
    bufp->fullBit(oldp+173,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_reg_write));
    bufp->fullBit(oldp+174,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_is_halted));
    bufp->fullBit(oldp+175,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_pc_to_reg));
    bufp->fullIData(oldp+176,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_alu_out),32);
    bufp->fullIData(oldp+177,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_dmem_data),32);
    bufp->fullCData(oldp+178,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_rd),5);
    bufp->fullIData(oldp+179,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_pc_plus_4),32);
    bufp->fullBit(oldp+180,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg));
    bufp->fullBit(oldp+181,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_reg_write));
    bufp->fullBit(oldp+182,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_is_halted));
    bufp->fullBit(oldp+183,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_pc_to_reg));
    bufp->fullIData(oldp+184,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1),32);
    bufp->fullIData(oldp+185,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_2),32);
    bufp->fullCData(oldp+186,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_rd),5);
    bufp->fullIData(oldp+187,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_pc_plus_4),32);
    bufp->fullCData(oldp+188,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_control),4);
    bufp->fullIData(oldp+189,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_in_1),32);
    bufp->fullIData(oldp+190,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_in_2),32);
    bufp->fullIData(oldp+191,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_result),32);
    bufp->fullBit(oldp+192,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_bcond));
    bufp->fullCData(oldp+193,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__functs),4);
    bufp->fullCData(oldp+194,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_op),2);
    bufp->fullCData(oldp+195,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_control),4);
    bufp->fullBit(oldp+196,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__reset));
    bufp->fullBit(oldp+197,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__clk));
    bufp->fullIData(oldp+198,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__update_pc),32);
    bufp->fullIData(oldp+199,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__update_BTB),32);
    bufp->fullBit(oldp+200,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__update_taken));
    bufp->fullIData(oldp+201,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__current_pc),32);
    bufp->fullIData(oldp+202,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__predicted_next_pc),32);
    bufp->fullBit(oldp+203,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__predicted_branch_taken));
    bufp->fullIData(oldp+204,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__i),32);
    bufp->fullBit(oldp+205,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag_match));
    bufp->fullCData(oldp+206,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__update_BTB_index),5);
    bufp->fullCData(oldp+207,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__update_PHT_index),5);
    bufp->fullCData(oldp+208,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__predict_BTB_index),5);
    bufp->fullCData(oldp+209,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__predict_PHT_index),5);
    bufp->fullCData(oldp+210,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__IF_ID_PHT_index),5);
    bufp->fullCData(oldp+211,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_PHT_index),5);
    bufp->fullCData(oldp+212,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__next_PHT),2);
    bufp->fullIData(oldp+213,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[0]),32);
    bufp->fullIData(oldp+214,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[1]),32);
    bufp->fullIData(oldp+215,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[2]),32);
    bufp->fullIData(oldp+216,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[3]),32);
    bufp->fullIData(oldp+217,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[4]),32);
    bufp->fullIData(oldp+218,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[5]),32);
    bufp->fullIData(oldp+219,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[6]),32);
    bufp->fullIData(oldp+220,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[7]),32);
    bufp->fullIData(oldp+221,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[8]),32);
    bufp->fullIData(oldp+222,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[9]),32);
    bufp->fullIData(oldp+223,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[10]),32);
    bufp->fullIData(oldp+224,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[11]),32);
    bufp->fullIData(oldp+225,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[12]),32);
    bufp->fullIData(oldp+226,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[13]),32);
    bufp->fullIData(oldp+227,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[14]),32);
    bufp->fullIData(oldp+228,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[15]),32);
    bufp->fullIData(oldp+229,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[16]),32);
    bufp->fullIData(oldp+230,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[17]),32);
    bufp->fullIData(oldp+231,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[18]),32);
    bufp->fullIData(oldp+232,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[19]),32);
    bufp->fullIData(oldp+233,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[20]),32);
    bufp->fullIData(oldp+234,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[21]),32);
    bufp->fullIData(oldp+235,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[22]),32);
    bufp->fullIData(oldp+236,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[23]),32);
    bufp->fullIData(oldp+237,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[24]),32);
    bufp->fullIData(oldp+238,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[25]),32);
    bufp->fullIData(oldp+239,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[26]),32);
    bufp->fullIData(oldp+240,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[27]),32);
    bufp->fullIData(oldp+241,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[28]),32);
    bufp->fullIData(oldp+242,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[29]),32);
    bufp->fullIData(oldp+243,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[30]),32);
    bufp->fullIData(oldp+244,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BTB[31]),32);
    bufp->fullIData(oldp+245,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[0]),27);
    bufp->fullIData(oldp+246,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[1]),27);
    bufp->fullIData(oldp+247,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[2]),27);
    bufp->fullIData(oldp+248,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[3]),27);
    bufp->fullIData(oldp+249,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[4]),27);
    bufp->fullIData(oldp+250,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[5]),27);
    bufp->fullIData(oldp+251,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[6]),27);
    bufp->fullIData(oldp+252,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[7]),27);
    bufp->fullIData(oldp+253,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[8]),27);
    bufp->fullIData(oldp+254,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[9]),27);
    bufp->fullIData(oldp+255,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[10]),27);
    bufp->fullIData(oldp+256,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[11]),27);
    bufp->fullIData(oldp+257,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[12]),27);
    bufp->fullIData(oldp+258,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[13]),27);
    bufp->fullIData(oldp+259,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[14]),27);
    bufp->fullIData(oldp+260,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[15]),27);
    bufp->fullIData(oldp+261,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[16]),27);
    bufp->fullIData(oldp+262,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[17]),27);
    bufp->fullIData(oldp+263,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[18]),27);
    bufp->fullIData(oldp+264,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[19]),27);
    bufp->fullIData(oldp+265,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[20]),27);
    bufp->fullIData(oldp+266,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[21]),27);
    bufp->fullIData(oldp+267,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[22]),27);
    bufp->fullIData(oldp+268,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[23]),27);
    bufp->fullIData(oldp+269,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[24]),27);
    bufp->fullIData(oldp+270,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[25]),27);
    bufp->fullIData(oldp+271,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[26]),27);
    bufp->fullIData(oldp+272,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[27]),27);
    bufp->fullIData(oldp+273,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[28]),27);
    bufp->fullIData(oldp+274,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[29]),27);
    bufp->fullIData(oldp+275,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[30]),27);
    bufp->fullIData(oldp+276,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__tag[31]),27);
    bufp->fullBit(oldp+277,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[0]));
    bufp->fullBit(oldp+278,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[1]));
    bufp->fullBit(oldp+279,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[2]));
    bufp->fullBit(oldp+280,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[3]));
    bufp->fullBit(oldp+281,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[4]));
    bufp->fullBit(oldp+282,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[5]));
    bufp->fullBit(oldp+283,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[6]));
    bufp->fullBit(oldp+284,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[7]));
    bufp->fullBit(oldp+285,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[8]));
    bufp->fullBit(oldp+286,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[9]));
    bufp->fullBit(oldp+287,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[10]));
    bufp->fullBit(oldp+288,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[11]));
    bufp->fullBit(oldp+289,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[12]));
    bufp->fullBit(oldp+290,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[13]));
    bufp->fullBit(oldp+291,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[14]));
    bufp->fullBit(oldp+292,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[15]));
    bufp->fullBit(oldp+293,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[16]));
    bufp->fullBit(oldp+294,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[17]));
    bufp->fullBit(oldp+295,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[18]));
    bufp->fullBit(oldp+296,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[19]));
    bufp->fullBit(oldp+297,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[20]));
    bufp->fullBit(oldp+298,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[21]));
    bufp->fullBit(oldp+299,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[22]));
    bufp->fullBit(oldp+300,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[23]));
    bufp->fullBit(oldp+301,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[24]));
    bufp->fullBit(oldp+302,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[25]));
    bufp->fullBit(oldp+303,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[26]));
    bufp->fullBit(oldp+304,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[27]));
    bufp->fullBit(oldp+305,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[28]));
    bufp->fullBit(oldp+306,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[29]));
    bufp->fullBit(oldp+307,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[30]));
    bufp->fullBit(oldp+308,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__valid[31]));
    bufp->fullCData(oldp+309,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[0]),2);
    bufp->fullCData(oldp+310,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[1]),2);
    bufp->fullCData(oldp+311,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[2]),2);
    bufp->fullCData(oldp+312,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[3]),2);
    bufp->fullCData(oldp+313,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[4]),2);
    bufp->fullCData(oldp+314,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[5]),2);
    bufp->fullCData(oldp+315,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[6]),2);
    bufp->fullCData(oldp+316,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[7]),2);
    bufp->fullCData(oldp+317,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[8]),2);
    bufp->fullCData(oldp+318,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[9]),2);
    bufp->fullCData(oldp+319,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[10]),2);
    bufp->fullCData(oldp+320,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[11]),2);
    bufp->fullCData(oldp+321,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[12]),2);
    bufp->fullCData(oldp+322,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[13]),2);
    bufp->fullCData(oldp+323,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[14]),2);
    bufp->fullCData(oldp+324,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[15]),2);
    bufp->fullCData(oldp+325,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[16]),2);
    bufp->fullCData(oldp+326,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[17]),2);
    bufp->fullCData(oldp+327,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[18]),2);
    bufp->fullCData(oldp+328,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[19]),2);
    bufp->fullCData(oldp+329,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[20]),2);
    bufp->fullCData(oldp+330,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[21]),2);
    bufp->fullCData(oldp+331,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[22]),2);
    bufp->fullCData(oldp+332,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[23]),2);
    bufp->fullCData(oldp+333,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[24]),2);
    bufp->fullCData(oldp+334,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[25]),2);
    bufp->fullCData(oldp+335,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[26]),2);
    bufp->fullCData(oldp+336,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[27]),2);
    bufp->fullCData(oldp+337,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[28]),2);
    bufp->fullCData(oldp+338,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[29]),2);
    bufp->fullCData(oldp+339,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[30]),2);
    bufp->fullCData(oldp+340,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__PHT[31]),2);
    bufp->fullCData(oldp+341,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__BHSR),5);
    bufp->fullBit(oldp+342,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__saturation_counter__DOT__branch_taken));
    bufp->fullCData(oldp+343,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__saturation_counter__DOT__current_state),2);
    bufp->fullCData(oldp+344,(vlSelfRef.top__DOT__cpu__DOT__branch_predictor__DOT__saturation_counter__DOT__next_state),2);
    bufp->fullCData(oldp+345,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__opcode),7);
    bufp->fullBit(oldp+346,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_jal));
    bufp->fullBit(oldp+347,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_jalr));
    bufp->fullBit(oldp+348,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__branch));
    bufp->fullBit(oldp+349,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__pc_to_reg));
    bufp->fullBit(oldp+350,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read));
    bufp->fullBit(oldp+351,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_to_reg));
    bufp->fullBit(oldp+352,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write));
    bufp->fullBit(oldp+353,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src));
    bufp->fullBit(oldp+354,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__reg_write));
    bufp->fullCData(oldp+355,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__alu_op),2);
    bufp->fullBit(oldp+356,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall));
    bufp->fullBit(oldp+357,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__reset));
    bufp->fullBit(oldp+358,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__clk));
    bufp->fullIData(oldp+359,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__addr),32);
    bufp->fullIData(oldp+360,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__din),32);
    bufp->fullBit(oldp+361,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__mem_read));
    bufp->fullBit(oldp+362,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__mem_write));
    bufp->fullIData(oldp+363,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__dout),32);
    bufp->fullIData(oldp+364,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__i),32);
    bufp->fullIData(oldp+365,(vlSelfRef.top__DOT__cpu__DOT__dmem__DOT__dmem_addr),32);
    bufp->fullCData(oldp+366,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__EX_rs1),5);
    bufp->fullCData(oldp+367,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__EX_rs2),5);
    bufp->fullCData(oldp+368,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_rd),5);
    bufp->fullBit(oldp+369,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_reg_write));
    bufp->fullCData(oldp+370,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__WB_rd),5);
    bufp->fullBit(oldp+371,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__WB_reg_write));
    bufp->fullCData(oldp+372,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__forward_ecall),2);
    bufp->fullCData(oldp+373,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__forward_rs1),2);
    bufp->fullCData(oldp+374,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__forward_rs2),2);
    bufp->fullBit(oldp+375,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__reset));
    bufp->fullBit(oldp+376,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__clk));
    bufp->fullIData(oldp+377,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__addr),32);
    bufp->fullIData(oldp+378,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__dout),32);
    bufp->fullIData(oldp+379,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__i),32);
    bufp->fullIData(oldp+380,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__imem_addr),32);
    bufp->fullIData(oldp+381,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__instruction),32);
    bufp->fullIData(oldp+382,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out),32);
    bufp->fullCData(oldp+383,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__opcode),7);
    bufp->fullBit(oldp+384,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__reset));
    bufp->fullBit(oldp+385,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__clk));
    bufp->fullBit(oldp+386,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__is_stall));
    bufp->fullIData(oldp+387,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__next_pc),32);
    bufp->fullIData(oldp+388,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__current_pc),32);
    bufp->fullBit(oldp+389,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__reset));
    bufp->fullBit(oldp+390,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__clk));
    bufp->fullCData(oldp+391,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1),5);
    bufp->fullCData(oldp+392,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2),5);
    bufp->fullCData(oldp+393,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd),5);
    bufp->fullIData(oldp+394,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd_din),32);
    bufp->fullBit(oldp+395,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__write_enable));
    bufp->fullIData(oldp+396,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1_dout),32);
    bufp->fullIData(oldp+397,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2_dout),32);
    bufp->fullIData(oldp+398,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[0]),32);
    bufp->fullIData(oldp+399,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[1]),32);
    bufp->fullIData(oldp+400,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[2]),32);
    bufp->fullIData(oldp+401,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[3]),32);
    bufp->fullIData(oldp+402,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[4]),32);
    bufp->fullIData(oldp+403,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[5]),32);
    bufp->fullIData(oldp+404,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[6]),32);
    bufp->fullIData(oldp+405,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[7]),32);
    bufp->fullIData(oldp+406,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[8]),32);
    bufp->fullIData(oldp+407,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[9]),32);
    bufp->fullIData(oldp+408,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[10]),32);
    bufp->fullIData(oldp+409,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[11]),32);
    bufp->fullIData(oldp+410,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[12]),32);
    bufp->fullIData(oldp+411,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[13]),32);
    bufp->fullIData(oldp+412,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[14]),32);
    bufp->fullIData(oldp+413,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[15]),32);
    bufp->fullIData(oldp+414,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[16]),32);
    bufp->fullIData(oldp+415,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[17]),32);
    bufp->fullIData(oldp+416,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[18]),32);
    bufp->fullIData(oldp+417,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[19]),32);
    bufp->fullIData(oldp+418,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[20]),32);
    bufp->fullIData(oldp+419,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[21]),32);
    bufp->fullIData(oldp+420,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[22]),32);
    bufp->fullIData(oldp+421,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[23]),32);
    bufp->fullIData(oldp+422,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[24]),32);
    bufp->fullIData(oldp+423,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[25]),32);
    bufp->fullIData(oldp+424,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[26]),32);
    bufp->fullIData(oldp+425,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[27]),32);
    bufp->fullIData(oldp+426,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[28]),32);
    bufp->fullIData(oldp+427,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[29]),32);
    bufp->fullIData(oldp+428,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[30]),32);
    bufp->fullIData(oldp+429,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[31]),32);
    bufp->fullIData(oldp+430,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__i),32);
    bufp->fullIData(oldp+431,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[0]),32);
    bufp->fullIData(oldp+432,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[1]),32);
    bufp->fullIData(oldp+433,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[2]),32);
    bufp->fullIData(oldp+434,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[3]),32);
    bufp->fullIData(oldp+435,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[4]),32);
    bufp->fullIData(oldp+436,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[5]),32);
    bufp->fullIData(oldp+437,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[6]),32);
    bufp->fullIData(oldp+438,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[7]),32);
    bufp->fullIData(oldp+439,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[8]),32);
    bufp->fullIData(oldp+440,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[9]),32);
    bufp->fullIData(oldp+441,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[10]),32);
    bufp->fullIData(oldp+442,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[11]),32);
    bufp->fullIData(oldp+443,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[12]),32);
    bufp->fullIData(oldp+444,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[13]),32);
    bufp->fullIData(oldp+445,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[14]),32);
    bufp->fullIData(oldp+446,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[15]),32);
    bufp->fullIData(oldp+447,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[16]),32);
    bufp->fullIData(oldp+448,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[17]),32);
    bufp->fullIData(oldp+449,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[18]),32);
    bufp->fullIData(oldp+450,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[19]),32);
    bufp->fullIData(oldp+451,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[20]),32);
    bufp->fullIData(oldp+452,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[21]),32);
    bufp->fullIData(oldp+453,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[22]),32);
    bufp->fullIData(oldp+454,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[23]),32);
    bufp->fullIData(oldp+455,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[24]),32);
    bufp->fullIData(oldp+456,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[25]),32);
    bufp->fullIData(oldp+457,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[26]),32);
    bufp->fullIData(oldp+458,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[27]),32);
    bufp->fullIData(oldp+459,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[28]),32);
    bufp->fullIData(oldp+460,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[29]),32);
    bufp->fullIData(oldp+461,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[30]),32);
    bufp->fullIData(oldp+462,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[31]),32);
    bufp->fullCData(oldp+463,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__ID_rs1),5);
    bufp->fullCData(oldp+464,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__ID_rs2),5);
    bufp->fullCData(oldp+465,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__ID_opcode),7);
    bufp->fullCData(oldp+466,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__EX_rd),5);
    bufp->fullBit(oldp+467,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__EX_mem_read));
    bufp->fullBit(oldp+468,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__EX_reg_write));
    bufp->fullCData(oldp+469,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__MEM_rd),5);
    bufp->fullBit(oldp+470,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__MEM_mem_read));
    bufp->fullBit(oldp+471,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__MEM_reg_write));
    bufp->fullBit(oldp+472,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__is_stall));
    bufp->fullBit(oldp+473,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__rs1_and_rs2_conditions));
    bufp->fullBit(oldp+474,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__rs1_conditions));
    bufp->fullBit(oldp+475,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__use_rs1));
    bufp->fullBit(oldp+476,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__use_rs2));
    bufp->fullBit(oldp+477,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__stall_by_load));
    bufp->fullBit(oldp+478,(vlSelfRef.top__DOT__cpu__DOT__stall_detection__DOT__stall_by_ecall));
}
